# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(blank=True, max_length=40, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=240)),
                ('role', models.CharField(choices=[('R', 'Regular'), ('A', 'Admin')], default='R', max_length=1)),
            ],
        ),
    ]
